let http_code = {
    100: 'Part of the request has been received by the server,Please wait',
    101: 'The server switches protocol',
    200: 'Request is OK',
    201: 'Request is complete, and a new resource is created',
    202: 'Request is accepted for processing, but the processing is not complete',
    203: 'Information in the entity header is from a local or third-party copy, not from the original server.',
    204: 'Only status code and a header are given in the response, but there is no entity-body in the reply.',
    205: 'User-agent should reset the document which sent this request',
    206: 'Server is returning partial data of the size requested',
    300: 'The request has more than one possible URL',
    301: 'The requested resource has moved permanently to a new URL ',
    302: 'The requested resource has moved temporarily to a new URL',
    303: 'The requested resource can be found under a different URL',
    304: 'Response has not been modified,continue using the cached version of the response',
    305: 'The requested resource must be accessed through the proxy mentioned in the Location header.',
    306: 'This response code is no longer used',
    307: 'The requested resource has moved temporarily to a new URL ,use same HTTP method',
    308: 'The requested resource has moved permanently to a new URL ,use same HTTP method',
    400: 'The server could not understand the request due to invalid syntax.',
    401: 'The requested page needs a username and a password',
    402: 'This response code is reserved for future use',
    403: 'Access is forbidden for the requested page',
    404: 'The server can not find the requested page',
    405: 'The HTTP Request method is not allowed.',
    406: 'The server can not send response accepted by the client.',
    407: 'Authentication with a proxy server is needed before this request can be served.',
    408: 'The request took longer than the server was prepared to wait.',
    409: 'Request conflicts with the current state of the server',
    410: 'The requested page is no longer available ',
    411: '"Content-Length" is not defined. The server require it',
    412: 'The client has indicated preconditions in its headers which the server does not meet.',
    413: 'The server will not accept the request, because the request entity is too large',
    414: 'The URI requested by the client is longer than the server is willing to interpret',
    415: 'The media format of the requested data is not supported by the server, so the server is rejecting the request',
    416: 'The range specified by the Range header field in the request can\'t be fulfilled',
    417: 'The expectation given in an Expect request-header field could not be met by this server',
    418: 'The server refuses the attempt to brew coffee with a teapot',
    422: 'The request was well-formed but was unable to be followed due to semantic errors',
    425: 'Indicates that the server is unwilling to risk processing a request that might be replayed',
    426: 'The server refuses to perform the request using the current protocol but might be willing to do so after the client upgrades to a different protocol',
    500: 'The request was not completed. The server met an unexpected condition.',
    501: 'The request method is not supported by the server and cannot be handled. The only methods that servers support are GET and HEAD.',
    502: 'The request was not completed. The server received an invalid response from the upstream server.',
    503: 'The request was not completed. The server is temporarily overloading or down',
    504: 'The gateway has timed out.',
    505: 'The server does not support the "http protocol" version'
}
let http_message = data => {
    return http_code[data];
};

export { http_message };